version: "3"

services:
  server:
    build:
      context: ./server
      args:
        app_env: "development"
    links:
      - "db"
    ports:
      - "3000:3000"
    volumes:
      - ./server:/src
      - ./server/node_modules
    tty: true
    container_name: server

  db:
    build:
      context: .
      dockerfile: ./db/Dockerfile
    restart: always
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: hoge
      MYSQL_PASSWORD: hoge
      MYSQL_DATABASE: deskApp
    volumes:
      - "./db:/config"
    ports:
      - 3306:3306
    container_name: db
